version: '3.1'

services:
  app:
    container_name: docker-golang-postgres
    restart: always
    build: .
    ports:
    - 80:3000
    links:
    - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080